### ISSUE TITLE
agent panics when `!isPty` and `len(session.Command()) == 0`

### ISSUE THREAD

**Issue by afriza** [shellhub-io/shellhub#1959]
### Panic detail
```
Sun Jun 19 17:36:58 2022 daemon.err sh[5210]: time="2022-06-19T10:36:58Z" level=info msg="Starting ShellHub" mode=multi-user version=v0.9.0
# ...
Sun Jun 19 17:41:36 2022 daemon.err sh[5210]: time="2022-06-19T10:41:36Z" level=info msg="Accepted password" user=redacted
Sun Jun 19 17:41:36 2022 daemon.err sh[5210]: time="2022-06-19T10:41:36Z" level=info msg="New session request" pty=false user=redacted
Sun Jun 19 17:41:36 2022 daemon.err sh[5210]: panic: runtime error: slice bounds out of range [1:0]
Sun Jun 19 17:41:36 2022 daemon.err sh[5210]:
Sun Jun 19 17:41:36 2022 daemon.err sh[5210]: goroutine 52 [running]:
Sun Jun 19 17:41:36 2022 daemon.err sh[5210]: github.com/shellhub-io/shellhub/agent/sshd.newCmd(0x1480840, {0x0, 0x0}, {0x0, 0x0}, {0x145c2b8, 0x11}, {0x0, 0x0, 0x0})
Sun Jun 19 17:41:36 2022 daemon.err sh[5210]: 	/redacted/shellhub/agent/sshd/cmd.go:30 +0x4dc
Sun Jun 19 17:41:36 2022 daemon.err sh[5210]: github.com/shellhub-io/shellhub/agent/sshd.(*Server).sessionHandler(0x1450a00, {0x542444, 0x18021c0})
Sun Jun 19 17:41:36 2022 daemon.err sh[5210]: 	/redacted/shellhub/agent/sshd/server.go:161 +0xbe8
Sun Jun 19 17:41:36 2022 daemon.err sh[5210]: github.com/gliderlabs/ssh.(*session).handleRequests.func1(0x18021c0)
Sun Jun 19 17:41:36 2022 daemon.err sh[5210]: 	/redacted/go/pkg/mod/github.com/gliderlabs/ssh@v0.3.3/session.go:262 +0x2c
Sun Jun 19 17:41:36 2022 daemon.err sh[5210]: created by github.com/gliderlabs/ssh.(*session).handleRequests
Sun Jun 19 17:41:36 2022 daemon.err sh[5210]: 	/redacted/go/pkg/mod/github.com/gliderlabs/ssh@v0.3.3/session.go:261 +0x578
```

### Steps to reproduce
```sh
ssh -p 2222 user@device@shellhub <<EOF
uname -a
EOF

```
The command above works if run directly without `@shellhub`.

### Workaround
```sh
ssh -p 2222 user@device@shellhub sh <<EOF
uname -a
EOF

```
notice the extra argument `sh` before `<<EOF`

**Comment by gustavosbarreto** [comment]
@afriza #1967 This is a temporary fix until we can fix the bug.

**Comment by afriza** [comment]
@gustavosbarreto Thanks.. at least not everyone connected will be affected by the panic..

**Comment by henrybarreto** [comment]
The PR https://github.com/shellhub-io/shellhub/pull/1968 try to fix it.
