### ISSUE TITLE
Running agent on Openshift

### ISSUE THREAD

**Issue by lapd-viosoft** [shellhub-io/shellhub#561]
Hi,
I'm having issue on running agent with non-root user. My scenario is
1. Rebuild agent as native mode
2. Create a pod (ubuntu 16.04) on Openshift. The pod is running with non-root user
3. Start agent as non-root user on this pod. I can see the connection request from dashboard. Accepting connection is ok
4. Trying to connect to pod using web interface, I got "Permission denied".

![image](https://user-images.githubusercontent.com/17825933/100990139-26551f00-3584-11eb-9485-011eba4f38fc.png)

The agent is crashed with this log:

```sh
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8c pc=0x7f06a89770ee]

runtime stack:
runtime.throw(0x91da9c, 0x2a)
        /usr/local/go/src/runtime/panic.go:774 +0x72
runtime.sigpanic()
        /usr/local/go/src/runtime/signal_unix.go:378 +0x47c

goroutine 11 [syscall]:
runtime.cgocall(0x811ad0, 0xc000178fc0, 0x40ec18)
        /usr/local/go/src/runtime/cgocall.go:128 +0x5b fp=0xc000178f90 sp=0xc000178f58 pc=0x40547b
github.com/shellhub-io/shellhub/agent/pkg/osauth._Cfunc_fgetspent(0x0, 0x0)
        _cgo_gotypes.go:142 +0x4a fp=0xc000178fc0 sp=0xc000178f90 pc=0x7a80ba
github.com/shellhub-io/shellhub/agent/pkg/osauth.AuthUser.func6(0x0, 0xc0003d45a0)
        /go/src/github.com/shellhub-io/shellhub/agent/pkg/osauth/auth.go:39 +0x56 fp=0xc000178ff8 sp=0xc000178fc0 pc=0x7a90f6
github.com/shellhub-io/shellhub/agent/pkg/osauth.AuthUser(0xc0004bacd8, 0x7, 0xc0004bad40, 0x7, 0xc000179200)
        /go/src/github.com/shellhub-io/shellhub/agent/pkg/osauth/auth.go:39 +0x22b fp=0xc000179168 sp=0xc000178ff8 pc=0x7a856b
github.com/shellhub-io/shellhub/agent/sshd.(*Server).passwordHandler(0xc0002a4300, 0x9c1800, 0xc000552520, 0xc0004bad40, 0x7, 0xc0004bad40)
        /go/src/github.com/shellhub-io/shellhub/agent/sshd/server.go:175 +0x17f fp=0xc000179318 sp=0xc000179168 pc=0x7ee7ff
github.com/shellhub-io/shellhub/agent/sshd.(*Server).passwordHandler-fm(0x9c1800, 0xc000552520, 0xc0004bad40, 0x7, 0xc0004bad40)
        /go/src/github.com/shellhub-io/shellhub/agent/sshd/server.go:170 +0x52 fp=0xc000179358 sp=0xc000179318 pc=0x7ef6f2
github.com/gliderlabs/ssh.(*Server).config.func1(0x9be620, 0xc0004e6980, 0xc00037502f, 0x7, 0x7, 0x0, 0x0, 0x40)
        /go/pkg/mod/github.com/gliderlabs/ssh@v0.3.0/server.go:122 +0xd4 fp=0xc0001793c8 sp=0xc000179358 pc=0x7e98b4
golang.org/x/crypto/ssh.(*connection).serverAuthenticate(0xc0004e6980, 0xc0005d72b0, 0x11, 0x40, 0x0)
        /go/pkg/mod/golang.org/x/crypto@v0.0.0-20200728195943-123391ffb6de/ssh/server.go:479 +0xb23 fp=0xc0001797c0 sp=0xc0001793c8 pc=0x7d5983
golang.org/x/crypto/ssh.(*connection).serverHandshake(0xc0004e6980, 0xc0005d72b0, 0x915aea, 0x1b, 0xcdb660)
        /go/pkg/mod/golang.org/x/crypto@v0.0.0-20200728195943-123391ffb6de/ssh/server.go:277 +0x59f fp=0xc000179890 sp=0xc0001797c0 pc=0x7d3baf
golang.org/x/crypto/ssh.NewServerConn(0x9bf940, 0xc000092600, 0xc0005d71e0, 0xc0005d71e0, 0x9bfa00, 0xc0004e9bf0, 0x120, 0x110)
        /go/pkg/mod/golang.org/x/crypto@v0.0.0-20200728195943-123391ffb6de/ssh/server.go:206 +0x17f fp=0xc000179938 sp=0xc000179890 pc=0x7d325f
github.com/gliderlabs/ssh.(*Server).HandleConn(0xc00016a000, 0x9bfa00, 0xc0004e9bf0)
        /go/pkg/mod/github.com/gliderlabs/ssh@v0.3.0/server.go:265 +0x199 fp=0xc000179a68 sp=0xc000179938 pc=0x7e67e9
github.com/shellhub-io/shellhub/agent/sshd.(*Server).HandleConn(...)
        /go/src/github.com/shellhub-io/shellhub/agent/sshd/server.go:77
main.main.func1(0x9bbbe0, 0xc000516620, 0xc0000e6500)
        /go/src/github.com/shellhub-io/shellhub/agent/main.go:129 +0x160 fp=0xc000179ac8 sp=0xc000179a68 pc=0x810280
```

Do we need root permission to establish ssh connection?
Thank!

**Comment by otavio** [comment]
@lapd-viosoft, thank you for reporting the issue.

In fact, it needs to have root access to be capable of validating the password. We certainly need to handle this exception better and log it accordingly, instead of crashing.

**Comment by lapd-viosoft** [comment]
Thank you for your feedback @otavio

**Comment by otavio** [comment]
@lapd-viosoft I'll let this open so we fix the exception so users have better feedback on this scenario.

**Comment by lapd-viosoft** [comment]
Hi @otavio 
This patch actually still require the agent run as root. For validating user password, we can use pam module. I think for some usecase, running agent as non root will provide better security. After user login to machine (via terminal on web), he is also can run sudo command without any issue (if he has permission).
This is an example code that I tried with pam module, and the agent can run with non-root just fine
```go
package main

import (
	"errors"
	"fmt"

	"github.com/msteinert/pam"
)
func AuthUser(user, passwd string) bool {
	serviceName:="passwd"
	t, err := pam.StartFunc(serviceName, user, func(s pam.Style, msg string) (string, error) {
		switch s {
		case pam.PromptEchoOff:
			return passwd, nil
		case pam.PromptEchoOn, pam.ErrorMsg, pam.TextInfo:
			return "", nil
		}
		return "", errors.New("Unrecognized PAM message style")
	})

	if err != nil {
		return false
	}

	if err = t.Authenticate(0); err != nil {
		return false
	}

	return true

}
func main() {
    username:= "demo"
    password:= "password"
	err := AuthUser(username, password)
	if err != nil {
		fmt.Println("Error")
	} else {
		fmt.Println("Auth")
	}
}
```

Notes:  to make the agent work with non-root account, using pam module as example above, I have to comment two lines of code in the function `func newCmd(u *osauth.User, shell, term, host string, command ...string) *exec.Cmd {` 
```sh
	cmd.Dir = u.HomeDir
	//cmd.SysProcAttr = &syscall.SysProcAttr{Setpgid: true}
	//cmd.SysProcAttr.Credential = &syscall.Credential{Uid: uint32(uid), Gid: uint32(gid), Groups: groups}
	return cmd
```

**Comment by otavio** [comment]
If desired, please open a PR with the proposed code so it can be reviewed and checked. We need to check if there is any drawback in using this approach as well.
